### ISSUE TITLE
[Bug] Corese docker do not accept multiple options in docker compose

### ISSUE THREAD

**Issue by MaillPierre** [Wimmics/corese#169]
**Issue Description:**

Multiple options for the corese server in the "OPTIONS" property of a docker-compose file trigger a parsing error

**Bug Details:**

When I try to use both the "-su" and "-o" options, I get `Parsing failed.  Reason: Unrecognized option: -owl -su`

**Steps to Reproduce:**

My project uses the [following config](https://github.com/Wimmics/IndeGx/blob/main/docker-compose.yml) for corese
```yaml
version: '3.8'
services:
  corese:
    image: wimmics/corese:latest
    hostname: corese
    environment:
      OPTIONS: "-owl -su"
      JVM_XMX: "15g"
    expose: 
      - "8080"
    volumes:
      - ./output:/usr/local/corese/log
      - ./config:/usr/local/corese/config
    extra_hosts:
      - host.docker.internal:host-gateway
```

I tried to replace `-owl` with `-o`, rearranging the order of the options.
Putting the options into a list :
```yaml
OPTIONS: 
    - "-owl" 
    - "-su"
```
returns a type error.
